Update codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -9,26 +9,36 @@ workflows:
         XCODE_PROJECT: "CleanerGuru.xcodeproj"
         XCODE_SCHEME: "CleanerGuru"
         APPLE_TEAM_ID: "2ZFFN6CVB4"
-        CERTIFICATE_PATH: "ios_distribution.p12"
+        PROVISIONING_PROFILE_SPECIFIER: "ios"
+        EXPORT_OPTIONS_PLIST: "./exportOptions.plist"
+        CERTIFICATE_PATH: "./ios_distribution.p12"
         CERTIFICATE_PASSWORD: "123456"
-        PROVISIONING_PROFILE_PATH: "ios.mobileprovision"
-        APP_STORE_CONNECT_API_KEY_PATH: "AuthKey_6V3PP83474.p8"
 
     scripts:
       - name: Install Fastlane
         script: |
           gem install fastlane --no-document
 
-      - name: Import Certificate
-        script: |
-          security import "$CERTIFICATE_PATH" -P "$CERTIFICATE_PASSWORD" -A
-
       - name: Increment build number
         script: |
-          currentBuildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "sources/Info.plist")
-          newBuildNumber=$((currentBuildNumber + 1))
-          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $newBuildNumber" "sources/Info.plist"
-          echo "Build number incremented to $newBuildNumber"
+          PLIST_PATH="./sources/Info.plist"
+          if [ -f "$PLIST_PATH" ]; then
+            currentBuildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$PLIST_PATH")
+            newBuildNumber=$((currentBuildNumber + 1))
+            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $newBuildNumber" "$PLIST_PATH"
+            echo "Build number incremented to $newBuildNumber"
+          else
+            echo "Info.plist not found at $PLIST_PATH"
+            exit 1
+          fi
+
+      - name: Import certificate
+        script: |
+          security create-keychain -p "" build.keychain
+          security import "$CERTIFICATE_PATH" -P "$CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k build.keychain
+          security list-keychains -s build.keychain
+          security unlock-keychain -p "" build.keychain
+          security set-keychain-settings -t 3600 -u build.keychain
 
       - name: Build & Sign IPA
         script: |
@@ -39,8 +49,8 @@ workflows:
             --export_method app-store \
             --output_directory build/ios/ipa \
             --output_name DeviceTunerPro26.ipa \
-            --export_options "./exportOptions.plist" \
-            --xcargs "DEVELOPMENT_TEAM=$APPLE_TEAM_ID CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER=$(basename $PROVISIONING_PROFILE_PATH .mobileprovision)"
+            --export_options "$EXPORT_OPTIONS_PLIST" \
+            --xcargs "DEVELOPMENT_TEAM=$APPLE_TEAM_ID PROVISIONING_PROFILE_SPECIFIER=$PROVISIONING_PROFILE_SPECIFIER CODE_SIGN_STYLE=Manual"
 
     artifacts:
       - build/ios/ipa/*.ipa
